---
abstract: 'Remove undesired keys from a hash (recursive)'
author:
  - 'Horea Gligan <gliganh@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.130880'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hash-Sanitize
no_index:
  directory:
    - t
    - inc
requires:
  Clone: 0
  Exporter: 0
  perl: 5.01
version: 0.03
